### PR TITLE
feat(config): add import type support

### PR DESCRIPTION
**Pull request by shaun-sweet**
Hello! I didn't see any contribution guidelines so I am just posting this in the hopes we can get this merged.  This adds support for [this typescript compiler option](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) 

Let me know what needs to be done to get this merged!  Thanks

### CODE REVIEW

**Review by ardeois — COMMENTED** [review]
Looks good, but can you update the readme please?
Thanks for the contribution!

**Comment by shaun-sweet** [comment]
You bet

**Comment by shaun-sweet** [comment]
Done!  I copied the naming convention and docs from other GQL plugins as well folks can use the top level config that shares across all the plugins :) thanks for the speedy reply!

**Review by ardeois — APPROVED** [review]

**Comment by hnrq** [comment]
Is there a way to keep importing enums as values instead of types?

**Comment by shaun-sweet** [comment]
> Is there a way to keep importing enums as values instead of types?

Yes https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-mock-data#useimplementingtypes-boolean-defaultvalue-false

**Pull request merged**
