### PR TITLE
feat: use `indefinite` to find the correct article

### PR DESCRIPTION
**Pull request by ardeois**
[indefinite](https://www.npmjs.com/package/indefinite) is able to find the correct indefinite article (`a` or `an`) for a given word.
It contains a list of irregular words for exceptions

BREAKING CHANGE: mock names for irregular words might change. Example:
 - before: `aUpload`
 - after: `anUpload`

### CODE REVIEW

**Comment by ardeois** [comment]
FYI @3nvi

**Comment by 3nvi** [comment]
Perfect! Thanks for that :D

**Comment by 3nvi** [comment]
@ardeois The example in the docs needs an update with regards to that. Still says `aUpdate...`

**Comment by ardeois** [comment]
> @ardeois The example in the docs needs an update with regards to that. Still says `aUpdate...`

Oops thanks

**Pull request merged**
